language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: generic

sudo: false

notifications:
  email: 
    on_failure: always

cache:
  - apt
  - directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    #- libzmq3-dev
    - libqt4-dev
    - qt4-dev-tools 
    - python-qt4-dev 
    - pyqt4-dev-tools
    - python-qt4
    - python-docutils
    - sqlite3

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then     brew update;                                                            fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then     brew install python gcc gfortran qt pyqtbrew install openssl readline;  fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then     export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages;   fi
  
  -  pip install docutils
  -  pip install -U pip

install:
  - travis_wait travis_retry pip install -r requirements.txt --upgrade

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then   ln -s /usr/lib/python2.7/dist-packages/PyQt4/ $VIRTUAL_ENV/lib/python2.7/site-packages/;    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then   ln -s /usr/lib/python2.7/dist-packages/sip.so $VIRTUAL_ENV/lib/python2.7/site-packages/;    fi

script: 
  - nosetests --with-coverage -v --cover-package=mosaic --cover-package=mosaicweb 
  - codecov
  
